export const productObj = {
  products: [
    {
      id: 1,
      title: "Tortellini con carne",
      description: "Tortellini fatti a mano ripieni di carne mista",
      price: 20,
      stock: 94,
      brand: "Casagrande pastificio",
      category: "Tortellini",
      thumbnail: "https://cdn.dummyjson.com/product-images/1/thumbnail.jpg",
      images: [
        "https://cdn.dummyjson.com/product-images/1/1.jpg",
        "https://cdn.dummyjson.com/product-images/1/2.jpg",
        "https://cdn.dummyjson.com/product-images/1/3.jpg",
        "https://cdn.dummyjson.com/product-images/1/4.jpg",
        "https://cdn.dummyjson.com/product-images/1/thumbnail.jpg",
      ],
    },
    {
      id: 2,
      title: "Tagliatelle",
      description: "Tagliatelle fatte e mano",
      price: 20,
      stock: 94,
      brand: "Casagrande pastificio",
      category: "Pasta Fresca",
      thumbnail: "https://cdn.dummyjson.com/product-images/1/thumbnail.jpg",
      images: [
        "https://cdn.dummyjson.com/product-images/1/1.jpg",
        "https://cdn.dummyjson.com/product-images/1/2.jpg",
        "https://cdn.dummyjson.com/product-images/1/3.jpg",
        "https://cdn.dummyjson.com/product-images/1/4.jpg",
        "https://cdn.dummyjson.com/product-images/1/thumbnail.jpg",
      ],
    },
    {
      id: 3,
      title: "Ravioli con merda",
      description: "Tortellini fatti a mano ripieni di merda mista",
      price: 20,
      stock: 94,
      brand: "Casagrande pastificio",
      category: "Ravioli",
      thumbnail: "https://cdn.dummyjson.com/product-images/1/thumbnail.jpg",
      images: [
        "https://cdn.dummyjson.com/product-images/1/1.jpg",
        "https://cdn.dummyjson.com/product-images/1/2.jpg",
        "https://cdn.dummyjson.com/product-images/1/3.jpg",
        "https://cdn.dummyjson.com/product-images/1/4.jpg",
        "https://cdn.dummyjson.com/product-images/1/thumbnail.jpg",
      ],
    },
  ],
  total: 100,
  skip: 0,
  limit: 30,
};
